Models/ErrorViewModel.cs
using System;

namespace SquareRoots.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SquareRoots.Models;

namespace SquareRoots.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RootsController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace SquareRoots.Controllers
{
    public class RootsController : Controller
    {
        [HttpGet]
        public ActionResult compare()
        {
            return View();
        }

        [HttpPost]
        public ActionResult compare(string firstnumber, string secondnumber)
        {
            double numberone = int.Parse(firstnumber);
            double numbertwo = int.Parse(secondnumber);
            double root1 = Math.Sqrt(numberone);
            double root2 = Math.Sqrt(numbertwo);
            int result = 0;

            ViewBag.num1 = numberone;
            ViewBag.num2 = numbertwo;
            ViewBag.Root1 = root1;
            ViewBag.Root2 = root2;
            if(ViewBag.Root1 > ViewBag.Root2)
            {
                result = 1;
            }
            else if(ViewBag.Root1 < ViewBag.Root2)
            {
                result = 2;
            }
            else if(ViewBag.Root1 == ViewBag.Root2)
            {
                result = 3;
            }
            else if(ViewBag.num1 < 0)
            {
                result = 4;
            }
            else if(ViewBag.num2 < 0)
            {
                result = 5;
            }
            ViewBag.Result = result;
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Roots/compare.cshtml
@{
    ViewData["Title"] = "Roots comparison";
}

<div class="text-center">
    <h1 class="display-4">Compare square roots of numbers</h1>
    <p>Fill in the numbers to compare their roots</p>
</div>

@{    
    if(ViewBag.Result == 0)
    {
        <div>
            <p>Fill in the numbers to compare their roots</p>
        </div>
    }
    else if(ViewBag.Result == 1)
    {
        <div>
            <p>The number @ViewBag.num1 with square root @ViewBag.Root1 has a higher square root than the number @ViewBag.num2 with square root @ViewBag.Root2</p>
        </div>
    }
    else if(ViewBag.Result == 2)
    {
        <div>
            <p>The number @ViewBag.num1 with square root @ViewBag.Root1 has a lower square root than the number @ViewBag.num2 with square root @ViewBag.Root2</p>
        </div>
    }
    else if(ViewBag.Result == 3)
    {
        <div>
            <p>Both numbers have the same square root. Please enter a new set of numbers</p>
        </div>
    }
    else if(ViewBag.Result == 4)
    {
        <div>
            <p>Error! The number @ViewBag.num1 has a negative value. Please enter a positive number</p>
        </div>
    }
    else if(ViewBag.Result == 5)
    {
        <div>
            <p>Error! The number @ViewBag.num2 has a negative value. Please enter a positive number</p>
        </div>
    }
}

<div>
    <form asp-controller="Roots" asp-action="compare" method="POST">
    <input type="number" placeholder ="first number" name="firstnumber"/>
    <input type="number" placeholder ="second number" name="secondnumber"/>
    <button type="submit">submit</button>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SquareRoots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SquareRoots</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SquareRoots - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>